[tool.pylint]
# Disable specific pylint warnings that are too strict for this project

[tool.pylint.messages_control]
disable = [
    "line-too-long",           # C0301: Ignore long lines (especially for user messages)
    "import-error",            # E0401: Ignore import errors for optional dependencies  
    "unused-import",           # W0611: Ignore unused imports (often needed for compatibility)
    "redefined-outer-name",    # W0621: Allow redefining names in different scopes
    "broad-except",            # W0703: Allow catching general Exception for robustness
    "bare-except",             # W0702: Allow bare except for compatibility fallbacks
    "too-many-locals",         # R0914: Allow many local variables in complex functions
    "too-many-statements",     # R0915: Allow many statements in main functions
    "too-many-branches",       # R0912: Allow complex branching for platform compatibility
    "missing-docstring",       # C0111: Don't require docstrings everywhere
    "invalid-name",            # C0103: Allow variable names like 'e', 'x', 'y'
    "unused-variable",         # W0613: Allow unused variables in fallback code
    "global-statement",        # W0603: Allow global statements when needed
    "consider-using-f-string", # C0209: Don't force f-strings everywhere
    "trailing-whitespace",     # C0303: Allow trailing whitespace
    "multiple-imports",        # C0410: Allow multiple imports on one line
    "wrong-import-position",   # C0413: Allow imports in different positions
    "import-outside-toplevel", # C0415: Allow imports inside functions for optional deps
]

[tool.pylint.format]
max-line-length = 120 # Allow longer lines than default 79

[tool.flake8]
max-line-length = 120
ignore = [
    "E501", # Line too long
    "E402", # Module level import not at top
    "F401", # Imported but unused
    "F841", # Local variable assigned but never used
    "W503", # Line break before binary operator
    "E722", # Do not use bare except
    "E203", # Whitespace before ':'
]

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
